"""New field in user model (last_seen)

Revision ID: 17506a967d81
Revises: 34d303240ff9
Create Date: 2020-09-30 10:21:50.233602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17506a967d81'
down_revision = '34d303240ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_last_seen'), 'user', ['last_seen'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last_seen'), table_name='user')
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
